<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encrypted_app_ticket.proto

namespace GPBMetadata;

class EncryptedAppTicket
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7010a1a656e637279707465645f6170705f7469636b65742e70726f74" .
            "6f121a41646f6377616e672e506870537465616d4170705469636b657422" .
            "ad010a12456e637279707465644170705469636b657412190a117469636b" .
            "65745f76657273696f6e5f6e6f18012001280d121b0a136372635f656e63" .
            "7279707465647469636b657418022001280d121c0a1463625f656e637279" .
            "70746564757365726461746118032001280d12270a1f63625f656e637279" .
            "707465645f6170706f776e6572736869707469636b657418042001280d12" .
            "180a10656e637279707465645f7469636b657418052001280c4205480180" .
            "0100620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

