<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encrypted_app_ticket.proto

namespace Adocwang\PhpSteamAppTicket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Adocwang.PhpSteamAppTicket.EncryptedAppTicket</code>
 */
class EncryptedAppTicket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 ticket_version_no = 1;</code>
     */
    private $ticket_version_no = 0;
    /**
     * Generated from protobuf field <code>uint32 crc_encryptedticket = 2;</code>
     */
    private $crc_encryptedticket = 0;
    /**
     * Generated from protobuf field <code>uint32 cb_encrypteduserdata = 3;</code>
     */
    private $cb_encrypteduserdata = 0;
    /**
     * Generated from protobuf field <code>uint32 cb_encrypted_appownershipticket = 4;</code>
     */
    private $cb_encrypted_appownershipticket = 0;
    /**
     * Generated from protobuf field <code>bytes encrypted_ticket = 5;</code>
     */
    private $encrypted_ticket = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ticket_version_no
     *     @type int $crc_encryptedticket
     *     @type int $cb_encrypteduserdata
     *     @type int $cb_encrypted_appownershipticket
     *     @type string $encrypted_ticket
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\EncryptedAppTicket::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 ticket_version_no = 1;</code>
     * @return int
     */
    public function getTicketVersionNo()
    {
        return $this->ticket_version_no;
    }

    /**
     * Generated from protobuf field <code>uint32 ticket_version_no = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTicketVersionNo($var)
    {
        GPBUtil::checkUint32($var);
        $this->ticket_version_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 crc_encryptedticket = 2;</code>
     * @return int
     */
    public function getCrcEncryptedticket()
    {
        return $this->crc_encryptedticket;
    }

    /**
     * Generated from protobuf field <code>uint32 crc_encryptedticket = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCrcEncryptedticket($var)
    {
        GPBUtil::checkUint32($var);
        $this->crc_encryptedticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cb_encrypteduserdata = 3;</code>
     * @return int
     */
    public function getCbEncrypteduserdata()
    {
        return $this->cb_encrypteduserdata;
    }

    /**
     * Generated from protobuf field <code>uint32 cb_encrypteduserdata = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCbEncrypteduserdata($var)
    {
        GPBUtil::checkUint32($var);
        $this->cb_encrypteduserdata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 cb_encrypted_appownershipticket = 4;</code>
     * @return int
     */
    public function getCbEncryptedAppownershipticket()
    {
        return $this->cb_encrypted_appownershipticket;
    }

    /**
     * Generated from protobuf field <code>uint32 cb_encrypted_appownershipticket = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCbEncryptedAppownershipticket($var)
    {
        GPBUtil::checkUint32($var);
        $this->cb_encrypted_appownershipticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes encrypted_ticket = 5;</code>
     * @return string
     */
    public function getEncryptedTicket()
    {
        return $this->encrypted_ticket;
    }

    /**
     * Generated from protobuf field <code>bytes encrypted_ticket = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEncryptedTicket($var)
    {
        GPBUtil::checkString($var, False);
        $this->encrypted_ticket = $var;

        return $this;
    }

}

